GET http://localhost:3000/user/


###

POST http://localhost:3000/register/ 
Content-Type: application/json

{
    "username":"henry",
    "password": "henry_the_developer"

}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "henry",
    "password": "henry_the_developer"
}

###
POST http://localhost:3000/upload/ 
Content-Type: application/json 

[
    {
        "userId" : "1" ,
        "id":"1" ,
        "title":"Durgamma",
        "body":"Jai Durgamma"
    }
]


###

GET http://localhost:3000/data/


###

DELETE http://localhost:3000/clear